'use strict';

var orbs = {
  canvas: document.getElementById('canvas'),
  view: {
    scale: 1,
    center: {x: canvas.width / 2, y: canvas.height / 2}
  },
  unit: canvas.width / (1000 * view.scale),
  level: 0,
  totalScore: 0,
  lives: 3,
  ship: null,
  asteroids: [],
  shots: [],
  faders: [],
  planets: [],
};

// var canvas,
//   u,
//   ctx,
//   name,
//   start,
//   destroyed,
//   launched,
//   burning,
//   dampenRot,
//   dampenBurn,
//   rot,
//   loaded,
//   asteroids,
//   shots,
//   faders,
//   exploded,
//   lives,
//   invincible,
//   planets,
//   ship,
//   gameEnd,
//   startScreen,
//   score,
//   bonus,
//   paused,
//   maxShots,
//   maxAsteroids,
//   scores,
//   scoreNumber,
//   newScore,
//   nameInput,
//   sunAngle;
